# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Croots <- function(x) {
    .Call(`_modelutil_Croots`, x)
}

lenFind <- function(Time, Infected) {
    .Call(`_modelutil_lenFind`, Time, Infected)
}

